disabled_rules:
  - file_length
  - function_body_length
  - line_length
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
  - vertical_whitespace
  - void_return
  - weak_delegate

included:
  - Sources
  - Tests

identifier_name:
  excluded:
    - id
    - ok
    - vc
